import type { Project, Transaction } from "./types";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-001",
    name: "Website Redesign",
    description: "รีดีไซน์เว็บไซต์บริษัทและระบบ CMS ใหม่",
    budget: 500000,
    startDate: "2026-01-15",
    endDate: "2026-06-30",
    owner: "สมชาย ใจดี",
  },
  {
    id: "proj-002",
    name: "Mobile App Launch",
    description: "พัฒนาและเปิดตัวแอปมือถือสำหรับลูกค้า",
    budget: 1200000,
    startDate: "2026-02-01",
    endDate: "2026-09-15",
    owner: "วิภา สุขใจ",
  },
  {
    id: "proj-003",
    name: "Office Renovation",
    description: "ปรับปรุงออฟฟิศชั้น 3 และพื้นที่ประชุม",
    budget: 350000,
    startDate: "2026-03-01",
    endDate: "2026-05-31",
    owner: "อนันต์ เก่งกาจ",
  },
  {
    id: "proj-004",
    name: "Marketing Campaign Q3",
    description: "แคมเปญการตลาดออนไลน์ไตรมาส 3",
    budget: 280000,
    startDate: "2026-07-01",
    endDate: "2026-09-30",
    owner: "พิมพ์ใจ รักงาน",
  },
];

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "txn-001",
    projectId: "proj-001",
    title: "ซื้อ Figma Team License",
    category: "ซอฟต์แวร์",
    transactionDate: "2026-01-20",
    amount: 45000,
    to: "Figma Inc.",
  },
  {
    id: "txn-002",
    projectId: "proj-001",
    title: "ค่าจ้าง Designer Freelance",
    category: "ค่าแรง",
    transactionDate: "2026-02-05",
    amount: 80000,
    to: "คุณนภา ดีไซน์",
  },
  {
    id: "txn-003",
    projectId: "proj-001",
    title: "Hosting & Domain ปีแรก",
    category: "ระบบ/เซิร์ฟเวอร์",
    transactionDate: "2026-02-15",
    amount: 25000,
    to: "Cloudflare",
  },
  {
    id: "txn-004",
    projectId: "proj-001",
    title: "ซื้อ Stock Photos",
    category: "สินทรัพย์",
    transactionDate: "2026-03-01",
    amount: 12000,
    to: "Unsplash+",
  },
  {
    id: "txn-005",
    projectId: "proj-002",
    title: "ค่าจ้าง iOS Developer",
    category: "ค่าแรง",
    transactionDate: "2026-02-10",
    amount: 150000,
    to: "คุณธนา โค้ดดี",
  },
  {
    id: "txn-006",
    projectId: "proj-002",
    title: "Apple Developer Account",
    category: "ซอฟต์แวร์",
    transactionDate: "2026-02-12",
    amount: 3500,
    to: "Apple Inc.",
  },
  {
    id: "txn-007",
    projectId: "proj-002",
    title: "ซื้อ MacBook Pro สำหรับ Dev",
    category: "อุปกรณ์",
    transactionDate: "2026-02-20",
    amount: 89000,
    to: "Apple Store",
  },
  {
    id: "txn-008",
    projectId: "proj-002",
    title: "ค่า API Backend Services",
    category: "ระบบ/เซิร์ฟเวอร์",
    transactionDate: "2026-03-05",
    amount: 42000,
    to: "AWS Thailand",
  },
  {
    id: "txn-009",
    projectId: "proj-002",
    title: "UI/UX Research Session",
    category: "ค่าแรง",
    transactionDate: "2026-03-15",
    amount: 28000,
    to: "Research Lab Co.",
  },
  {
    id: "txn-010",
    projectId: "proj-003",
    title: "ซื้อเฟอร์นิเจอร์สำนักงาน",
    category: "อุปกรณ์",
    transactionDate: "2026-03-05",
    amount: 120000,
    to: "IKEA Thailand",
  },
  {
    id: "txn-011",
    projectId: "proj-003",
    title: "ค่าจ้างช่างตกแต่ง",
    category: "ค่าแรง",
    transactionDate: "2026-03-10",
    amount: 95000,
    to: "บจก. ตกแต่งสวย",
  },
  {
    id: "txn-012",
    projectId: "proj-003",
    title: "วัสดุทาสีและพื้น",
    category: "วัสดุ",
    transactionDate: "2026-03-12",
    amount: 45000,
    to: "HomePro",
  },
  {
    id: "txn-013",
    projectId: "proj-004",
    title: "Facebook Ads Credit",
    category: "โฆษณา",
    transactionDate: "2026-07-02",
    amount: 50000,
    to: "Meta Platforms",
  },
  {
    id: "txn-014",
    projectId: "proj-004",
    title: "จ้าง Influencer 3 คน",
    category: "การตลาด",
    transactionDate: "2026-07-08",
    amount: 75000,
    to: "Creator Agency",
  },
];

export const TRANSACTION_CATEGORIES = [
  "ค่าแรง",
  "อุปกรณ์",
  "ซอฟต์แวร์",
  "ระบบ/เซิร์ฟเวอร์",
  "วัสดุ",
  "โฆษณา",
  "การตลาด",
  "เดินทาง",
  "สินทรัพย์",
  "อื่นๆ",
] as const;
